title: SensorFu
url: https://sensorfu.com
timezone: UTC

include: [".well-known"]

# Build settings
# Disable github pages default theme
theme: null

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
